export const data = [
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 1
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 2
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 3
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 1
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 3
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 2
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 1
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 2
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 2
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 2
  },
  {
    id: 'NM-1',
    add: 'Sardor Omonov',
    important: 'Oddiy',
    type: 'Bug',
    title: "Yer hisonotta user qo'shish",
    project: 'Yer hisonot',
    main: 'Solijonov Muhammad Ali',
    assisten: 'Abdulloh Abdurazzoqov',
    dec: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
    status: 2
  }
]
